### ISSUE TITLE
"Fade variant" does not function on iOS

### ISSUE THREAD

**Issue by andyspocket** [tornqvist/dialog#2]
All the rest work nicely. But for some reason "Fade variant" does not function on iOS.
Just throws up the faded background with no dialog box every shown.

**Comment by tornqvist** [comment]
Fixed.
Turned out iOS was trying to animate the visibility attribute

**Comment by andyspocket** [comment]
Odd seemed to work with ios for a bit. Now "fade variant" still not working. 
Just all faded background no dialog, then after clicking it the others also fail.
